version: "3.8"

services:
  app:
    container_name: frontend_container
    build: .
      # context: .
    ports:
      - 80:3000
    environment:
      - REACT_APP_DEFAULT_HOTEL_ID=64252efb369c403b60effae8 
      - REACT_APP_FRONTEND_SERVER_DOMAIN=http://hotel.wikitoria.in
      
      - REACT_APP_API_SERVER_DOMAIN=https://hotelapi.wikitoria.in
      - REACT_APP_API_SERVER_URI=https://hotelapi.wikitoria.in/api    
      - REACT_APP_API_SERVER_SOCKET_PORT=443 
      