version: "3.8"

services:
  app:
    container_name: frontend_container
    build: .
      # context: .
    ports:
      - 80:3000
    environment:
      - REACT_APP_API_URI=https://hotelapi.wikitoria.in/api
      # - REACT_APP_BASE_URI=http://hotel.wikitoria.in
      - REACT_APP_BASE_URI=https://hotel.wikitoria.in
      - REACT_APP_API_IP=43.239.110.22
      - SOCKET_PORT=3001
      - HTTPS=true
      - SSL_CRT_FILE=.//sslcert//certificate.crt
      - SSL_KEY_FILE=.//sslcert//private.key     