version: "3.8"

services:
  app:
    container_name: frontend_container
    # image: docker-react-i
    build: .
      # context: .
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URI=https://hotelapi.wikitoria.in/api
      - REACT_APP_BASE_URI=http://localhost:3000/